Task1_Homework/Task1_Homework/Models/EventsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task1_Homework.Business;

namespace Task1_Homework.Models
{
    public class EventsViewModel
    {
        public City[] Cities { get; set; }

        public Venue[] Venues { get; set; }
    }
}

Task1_Homework/Task1_Homework/Controllers/Api/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Task1_Homework.Business;
using Task1_Homework.Business.Queries;
using Task1_Homework.Business.Services.IServices;
using Task1_Homework.Controllers.Api.Models;
using AutoMapper;
using Microsoft.AspNetCore.Http;

namespace Task1_Homework.Controllers.Api
{
    [Route("api/v1/[controller]")]
    [ApiController]
    public class EventsController : ControllerBase
    {
        private readonly IEventService eventService;
        private readonly IMapper mapper;

        public EventsController(IEventService eventService,IMapper mapper)
        {
            this.eventService = eventService;
            this.mapper = mapper;
        }

        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<EventResource>), StatusCodes.Status200OK)]
        public ActionResult GetPaggedData([FromQuery]PagedData<Event> pagedData)
        {
            if(pagedData.Search != null)
            {
                pagedData.Data = eventService.GetEventsBySearch(pagedData.Search).ToList();
            }
            pagedData.Data = eventService.GetFiltredEvents(pagedData).ToList();
            pagedData.TotalNumber = pagedData.Data.Count();
            HttpContext.Response.Headers.Add("x-total-count", pagedData.TotalNumber.ToString());
            HttpContext.Response.Headers.Add("x-current-page", pagedData.CurrentPage.ToString());
            return Ok(mapper.Map<IEnumerable<EventResource>>(pagedData.Data));
        }


        [HttpGet]
        [Route("autocomplete")]
        [ProducesResponseType(typeof(IEnumerable<string>), StatusCodes.Status200OK)]
        public ActionResult GetAutocompleteData([FromQuery]string q)
        {
            var list = eventService.GetEventsNameForAutocomplete(q);
            return Ok(list);
        } 
    }
}

Task1_Homework/Task1_Homework/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task1_Homework.Models;
using Task1_Homework.Business;
using Task1_Homework.Business.Models;
using Microsoft.Extensions.Localization;
using Task1_Homework.Business.Database;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Task1_Homework.Business.Services.IServices;

namespace Task1_Homework.Controllers
{
    public class EventController : Controller
    {
        private readonly IUserService userService;
        private readonly ITicketService ticketService;
        private readonly IEventService eventService;
        private readonly IVenueService venueService;
        private readonly ICityService cityService;

        public EventController(IUserService userService,ITicketService ticketService, IEventService eventService, IVenueService venueService, ICityService cityService)
        {
            this.userService = userService;
            this.ticketService = ticketService;
            this.eventService = eventService;
            this.venueService = venueService;
            this.cityService = cityService;
        }

         public IActionResult Index()
        {
            var ev = new EventsViewModel()
            {
                Cities = cityService.GetCities().ToArray(),
                Venues = venueService.GetVenues().ToArray()
            };

            if (User.Identity.Name != null)
            {
                ViewBag.UserRole = userService.GetUserRole(User.Identity.Name);
            }

            return View(ev);
        }

        public async Task<IActionResult> Buy([FromRoute] int? id)
        {
            if (id != null)
            {
                var events = eventService.GetEventById(id);

                events.Tickets = await ticketService.GetTicketsByEventIdForIdentityUser(id , User.Identity.Name);

                return View("Buy", events);
            }

            return NotFound();
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                var venues = new SelectList(venueService.GetVenues(), "Id", "Name");
                ViewBag.Venues = venues;
                var ev = eventService.GetEventById(id);
                return View(ev);
            }
            return NotFound();
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Edit(Event model)
        {
            if (ModelState.IsValid)
            {
                await eventService.EditSave(model);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Edit");
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id != null)
            {
                var @event = eventService.GetEventById(id);
                return PartialView("_Delete", @event);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                var ev = eventService.GetEventById(id);
                if (ev != null)
                {
                    await eventService.Delete(ev);
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

Task1_Homework/Task1_Homework/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Task1_Homework.Business;
using Task1_Homework.Business.Database;
using Task1_Homework.Business.Models;
using Task1_Homework.Business.Services.IServices;
using Task1_Homework.Models;

namespace Task1_Homework.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IOrderService orderService;
        private readonly ITicketService ticketService;

        public OrderController(UserManager<User> userManager, IOrderService orderService, ITicketService ticketService)
        {
            this.userManager = userManager;
            this.orderService = orderService;
            this.ticketService = ticketService;
        }

        public async Task<IActionResult> Create([FromRoute] int? id)
        {
            if (id != null)
            {
                var ticket = ticketService.GetTicketById(id);
                var buyer = await userManager.FindByNameAsync(User.Identity.Name);

                var model = new OrderCreateViewModel
                {
                    TicketId = ticket.Id,
                    BuyerId = buyer.Id
                };

                ViewData["EventName"] = ticket.Event.Name;
                ViewData["TicketPrice"] = ticket.Price;
                ViewData["BuyerName"] = buyer.UserName;

                return View("Create", model);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderCreateViewModel model)
        {
            if (ModelState.IsValid) {
                var order = new Order
                {
                    TicketId = model.TicketId,
                    BuyerId = model.BuyerId,                       
                    Status = TicketSaleStatus.Confirmation
                };
                await orderService.Save(order);
                return View("BuyRequest");
            }
            return RedirectToAction("Create", model);
        }

        public IActionResult BuyRequest()
        {            
            return View();
        }

        public IActionResult SalesRequests()
        {
            var orders = orderService.GetSalesRequestsForIdentityUser(User.Identity.Name).Result;

            if (orders != null)
            {
                var model = new OrderViewModel
                {
                    Orders = orders.ToArray()
                };

                return View(model);
            }

            return NotFound();
        }


        public IActionResult Accept([FromRoute] int? id)
        {
            if (id != null)
            {
                var order = orderService.GetOrderById(id);

                if (order != null)
                {
                    return PartialView("_Accept", order);
                }
            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Accept(Order model)
        {
            if (ModelState.IsValid)
            {
                var order = orderService.GetOrderById(model.Id);
                var user = await userManager.FindByNameAsync(HttpContext.User.Identity.Name);

                if (order.Ticket.SellerId != user.Id) 
                    return Forbid();

                await orderService.EditSave(order, model.TrackNumber);
                return RedirectToAction("SalesRequests");
            }
            return NotFound();
        }

        public IActionResult MyOrders()
        {
            var orders = orderService.GetOrdersForIdentityUser(User.Identity.Name).Result;

            if (orders != null)
            {
                var model = new OrderViewModel
                {
                    Orders = orders.ToArray()
                };

                return View(model);
            }

            return NotFound();
        }

        public async Task<IActionResult> Reject([FromRoute]int? id)
        {
            if (id != null)
            {
                var order = orderService.GetOrderById(id);
                order.Status = TicketSaleStatus.Rejected;
                await orderService.EditSave(order);

                return RedirectToAction("SalesRequests");
            }

            return NotFound();
        }

        public async Task<IActionResult> CancelOrder([FromRoute]int? id)
        {
            if (id != null)
            {
                await orderService.Delete(orderService.GetOrderById(id));
                return RedirectToAction("MyOrders");
            }

            return NotFound();
        }
    }
}

Task1_Homework/Task1_Homework/Controllers/TicketController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Task1_Homework.Business;
using Task1_Homework.Business.Database;
using Task1_Homework.Business.Models;
using Task1_Homework.Business.Services.IServices;
using Task1_Homework.Models;

namespace Task1_Homework.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly ITicketService ticketService;
        private readonly IEventService eventService;

        public TicketController(UserManager<User> userManager, ITicketService ticketService, IEventService eventService)
        {
            this.userManager = userManager;
            this.ticketService = ticketService;
            this.eventService = eventService;
        }

        public IActionResult CreateTicket([FromRoute] int? id)
        {
            if (id != null)
            {
                var @event = eventService.GetEventById(id);

                if (@event == null)
                {
                    return BadRequest();
                }

                var model = new TicketCreateViewModel
                {
                    EventId = @event.Id,
                    EventName = @event.Name
                };
                return PartialView("CreateTicket", model);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTicket(TicketCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var ticket = new Ticket
                {
                    EventId = model.EventId,
                    Price = model.Price,
                    SellerId = (await userManager.FindByNameAsync(User.Identity.Name)).Id
                };

                ticket.Status = TicketSaleStatus.Sale;
                await ticketService.Save(ticket);
                return RedirectToAction("Index", "Event");
            }
            
            return RedirectToAction("CreateTicket", model);
        }

        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                var ticket = ticketService.GetTicketById(id);
                return View("Edit", ticket);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Ticket model)
        {
            if (ModelState.IsValid)
            {
                await ticketService.EditSave(model);
                return RedirectToAction("Index");
            }

            return BadRequest();
        }


        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id != null)
            {
                var ticket = ticketService.GetTicketById(id);
                return PartialView("_Delete", ticket);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                var ticket = ticketService.GetTicketById(id);
                if (ticket != null)
                {
                    await ticketService.Delete(ticket);
                    return RedirectToAction("Profile", "User");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> UserTickets()
        {
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            var tickets = await ticketService.GetTicketsByUserId(user.Id);
            return View("UserTickets", tickets);
        }
    }
}

Task1_Homework/Task1_Homework/Views/Event/Buy.cshtml
@model Task1_Homework.Business.Event
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Buy"];
}

<h1 class="loginpagetext buytext">@Localizer["Event Page"]</h1>
<div class="blockbuy">
    <div id="template blockbuy">
        <div id="picture">
            <img src="~/img/@Model.Banner" width="230" height="350" vspace="50" hspace="30" class="leftimg" />
        </div>
        <div id="modDialog" class="modal fade">
            <div id="dialogContent" class="modal-dialog"></div>
        </div>
        <div class="content">
            <div id="header">
                <h3 align="center">@Model.Name</h3>
            </div>
            <div id="description">
                <p>@Html.Raw(Model.Description)</p>
            </div>
            <div class="dateev">
                <h6 class="h66">@Model.Date <br />  @Localizer["on"] @Model.Venue.Name</h6>
            </div>
            <div>
                @if(User.Claims.Any())
                {
                @Html.ActionLink("Sell Ticket", "CreateTicket", "Ticket", new { id = Model.Id }, new { @class = "btnsellticket compItem" })
                }
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>@Localizer["Price"]</th>
                    <th>@Localizer["Seller"]</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var ticket in Model.Tickets)
                {
                    @if (ticket.Status == Task1_Homework.Business.TicketSaleStatus.Sale)
                    {
                        <tr>
                            <td>@ticket.Price</td>
                            <td>@ticket.Seller.UserName</td>
                            <td>
                                @Html.ActionLink("Buy", "Create", "Order", new { id = ticket.Id }, new { @class = "btnbuy" })
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

Task1_Homework/Task1_Homework/Views/Event/Edit.cshtml
@model Task1_Homework.Business.Event

@{
    ViewData["Title"] = "Edit Event";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="loginpagetext buytext">Edit</h1>

<h4 class="loginpagetext">Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" class="textformedit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VenueId" class="control-label"></label>
                <select asp-for="VenueId" class="form-control" asp-items="@ViewBag.Venues"></select>
                <span asp-validation-for="VenueId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Banner" class="control-label"></label>
                <input asp-for="Banner" type="file" class="form-control" />
                <span asp-validation-for="Banner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btnsend" />
            </div>
            <div>
                <a asp-action="Index" class="btncancel">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task1_Homework/Task1_Homework/Views/Event/Index.cshtml
@model EventsViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Events"];
}



<div class="block2ForEvent">
    <h1 align="center" class="h11">@Localizer["List Of Events"]</h1>
    <div class="container-fluid pt-3">
        <div class="input-wrapper searchindex">
            <input id="inputsearch" type="search" class="inputsearch basicAutoComplete" placeholder="Search…">
        </div>
        <div class="block1 selects ">
            <div class="selectindex">
                <select name="cities" id="cities" type="text" multiple title="Select City" class=" selectpicker">
                </select>
            </div>
            <div class="selectindex">
                <select name="venues" id="venues" type="text" multiple class=" selectpicker" title="Select Venue" disabled>
                </select>
            </div>
            <div class="selectindex">
                <select name="venues" id="sortby" type="text" class=" selectpicker">
                    <option value="Date">Date</option>
                    <option value="Name">Name</option>
                </select>
            </div>
        </div>
        <div id="items">

        </div>
        <nav aria-label="..." class="napag">
            <div id="paged">
            </div>
        </nav>
    </div>
</div>

@section Scripts
{
    <script>
        const role = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.UserRole));
    </script>
    <script src="~/js/events.index.js" type="module" defer></script>
}

Task1_Homework/Task1_Homework/Views/Event/_Delete.cshtml
@model Task1_Homework.Business.Event

@{
    ViewData["Title"] = "Delete Confirm";
}

<div class="modal-content ">
    <div class="modal-header">
        <h6 class="">Are you sure you want to delete this event?</h6>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name):
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Date):
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
        </dl>
        <form asp-action="Delete" asp-controller="Event">
            <input type="submit" value="Delete" class="btnsend" /> |
            <a asp-action="Index" asp-controller="Event" class="btncancel">Cancel</a>
        </form>
    </div>
</div>