Task1_Homework/Task1_Homework/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Task1_Homework.Business;
using Task1_Homework.Business.Database;
using Task1_Homework.Business.Models;
using Task1_Homework.Business.Services.IServices;
using Task1_Homework.Models;

namespace Task1_Homework.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly ICityService cityService;
        private readonly IEventService eventService;
        private readonly ITicketService ticketService;
        private readonly IVenueService venueService;

        public AdminController(ICityService cityService, IEventService eventService, ITicketService ticketService, IVenueService venueService)
        {
            this.cityService = cityService;
            this.eventService = eventService;
            this.ticketService = ticketService;
            this.venueService = venueService;
        }
        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult CreateEvent()
        {
            var venues = new SelectList(venueService.GetVenues(), "Id", "Name");
            ViewBag.Venues = venues;
            return View("CreateEvent");
        }

        [HttpPost]
        public async Task<IActionResult> CreateEvent(EventCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var @event = new Event
                {
                    Banner = model.Banner,
                    Date = model.Date,
                    Description = model.Description,
                    VenueId = model.VenueId,
                    Name = model.Name
                };
                await eventService.Save(@event);
                return RedirectToAction("Index");
            }
            return RedirectToAction("CreateEvent");
        }

        public IActionResult CreateCity()
        {
            return View("City/CreateCity");
        }

        [HttpPost]
        public async Task<IActionResult> CreateCity(CityCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var city = new City
                {
                    Name = model.Name,
                    Country = model.Country
                };

                await cityService.Save(city);
                return RedirectToAction("City/GetCityList");
            }

            return RedirectToAction("City/CreateCity");
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> EditCity(int id)
        {
            var city = await cityService.GetCityById(id);

            return View("City/EditCity",city);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> EditCity(City model)
        {
            await cityService.EditSave(model);
            return RedirectToAction("City/GetCityList");
        }

        [ActionName("DeleteCity")]
        public async Task<IActionResult> ConfirmDeleteCity(int? id)
        {
            if (id != null)
            {
                var city = await cityService.GetCityById(id);
                return PartialView("City/_DeleteCity", city);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCity(int? id)
        {
            if (id != null)
            {
                var city = await cityService.GetCityById(id);
                if (city != null)
                {
                    await cityService.Delete(city);
                    return RedirectToAction("City/GetCityList");
                }
            }
            return NotFound();
        }

        public IActionResult GetCityList()
        {
            var cvm = new CitiesViewModel
            {
                Cities = cityService.GetCities().ToArray()
            };

            return View("City/GetCityList", cvm);
        }

        public IActionResult CreateVenue()
        {
            var cities = new SelectList(cityService.GetCities(), "Id", "Name");
            ViewBag.Cities = cities;
            return View("Venue/CreateVenue");
        }

        [HttpPost]
        public async Task<IActionResult> CreateVenue(VenueCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var venue = new Venue
                {
                    Name = model.Name,
                    Adress = model.Adress,
                    CityId = model.CityId,
                };

                await venueService.Save(venue);
                return RedirectToAction("Venue/GetVenueList");
            }

            return RedirectToAction("Venue/CreateVenue");
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult EditVenue(int id)
        {
            var cities = new SelectList(cityService.GetCities(), "Id", "Name");
            ViewBag.Cities = cities;
            var venue = venueService.GetVenueById(id);
            return View("Venue/EditVenue",venue);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> EditVenue(Venue model)
        {
            if (ModelState.IsValid)
            {
                await venueService.EditSave(model);
                return RedirectToAction("Venue/GetVenueList");
            }
            return NotFound();
        }

        [ActionName("DeleteVenue")]
        public IActionResult ConfirmDeleteVenue(int? id)
        {
            if (id != null)
            {
                Venue venue = venueService.GetVenueById(id);
                return PartialView("Venue/_DeleteVenue", venue);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteVenue(int? id)
        {
            if (id != null)
            {
                var venue = venueService.GetVenueById(id);
                if (venue != null)
                {
                    await venueService.Delete(venue);
                    return RedirectToAction("Venue/GetVenueList");
                }
            }
            return NotFound();
        }

        public IActionResult GetVenueList()
        {
            var vvm = new VenueViewModel
            {
                Venues = venueService.GetVenues().ToArray()
            };
            return View("Venue/GetVenueList" ,vvm);
        }
    }
}

Task1_Homework/Task1_Homework/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Task1_Homework.Business;
using Task1_Homework.Models;

namespace Task1_Homework.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => PartialView("_Create");

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Task1_Homework/Task1_Homework/Views/Admin/CreateCity.cshtml
@model Task1_Homework.Business.City

@{
    ViewData["Title"] = "CreateCity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateCity</h1>

<h4>City</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCity">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task1_Homework/Task1_Homework/Views/Admin/CreateEvent.cshtml
@model EventCreateViewModel

@{
    ViewData["Title"] = "Create Event";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="loginpagetext buytext" >Create New Event</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" class="buytextni22">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Banner" class="control-label"></label>
                <input asp-for="Banner" type="file" class="form-control" />
                <span asp-validation-for="Banner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VenueId" class="control-label"></label>
                <select asp-for="VenueId" class="form-control" asp-items="@ViewBag.Venues"></select>
                <span asp-validation-for="VenueId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" asp-action="CreateEvent" class="btnsend" />
                <a asp-action="Index" asp-controller="Admin" class="btncancel">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task1_Homework/Task1_Homework/Views/Admin/CreateVenue.cshtml
@model Task1_Homework.Business.Venue

@{
    ViewData["Title"] = "CreateVenue";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateVenue</h1>

<h4>Venue</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateVenue">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label"></label>
                <select asp-for="CityId" class="form-control" asp-items="@ViewBag.Cities"></select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task1_Homework/Task1_Homework/Views/Admin/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Admin Page"];
}

@if (User.Identity.IsAuthenticated)
{
<h1 class="loginpagetext buytext">Admin page</h1>
<hr />
<div class="row">
    <div class="">
        <h3 class="loginpagetext">Admin functions</h3>
        <form asp-action="Index">
            <div class="nav-item">
                <div class="btn-group-vertical dispadmin">                                    
                        @Html.ActionLink("Role Manager", "Index", "Roles", new { }, new { @class = "btnem" })
                        @Html.ActionLink("Cities List", "GetCityList", "Admin", new { }, new { @class = "btnem" })
                        @Html.ActionLink("Venues List", "GetVenueList", "Admin", new { }, new { @class = "btnem" })
                        @Html.ActionLink("Create New Event", "CreateEvent", "Admin", new { }, new { @class = "btnem2" })
                </div>
            </div>
        </form>
    </div>
</div>
}