Task1_Homework/Task1_Homework/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task1_Homework.Business;
using Task1_Homework.Business.Models;

namespace Task1_Homework.Models
{
    public class OrderViewModel
    {
        public Order[] Orders { get; set; }
    }
}

Task1_Homework/Task1_Homework/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task1_Homework.Models;
using Task1_Homework.Business;
using Task1_Homework.Business.Models;
using Microsoft.Extensions.Localization;
using Task1_Homework.Business.Database;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Task1_Homework.Business.Services.IServices;

namespace Task1_Homework.Controllers
{
    public class EventController : Controller
    {
        private readonly IUserService userService;
        private readonly ITicketService ticketService;
        private readonly IEventService eventService;
        private readonly IVenueService venueService;
        private readonly ICityService cityService;

        public EventController(IUserService userService,ITicketService ticketService, IEventService eventService, IVenueService venueService, ICityService cityService)
        {
            this.userService = userService;
            this.ticketService = ticketService;
            this.eventService = eventService;
            this.venueService = venueService;
            this.cityService = cityService;
        }

         public IActionResult Index()
        {
            var ev = new EventsViewModel()
            {
                Cities = cityService.GetCities().ToArray(),
                Venues = venueService.GetVenues().ToArray()
            };

            if (User.Identity.Name != null)
            {
                ViewBag.UserRole = userService.GetUserRole(User.Identity.Name);
            }

            return View(ev);
        }

        public async Task<IActionResult> Buy([FromRoute] int? id)
        {
            if (id != null)
            {
                var events = eventService.GetEventById(id);

                events.Tickets = await ticketService.GetTicketsByEventIdForIdentityUser(id , User.Identity.Name);

                return View("Buy", events);
            }

            return NotFound();
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                var venues = new SelectList(venueService.GetVenues(), "Id", "Name");
                ViewBag.Venues = venues;
                var ev = eventService.GetEventById(id);
                return View(ev);
            }
            return NotFound();
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Edit(Event model)
        {
            if (ModelState.IsValid)
            {
                await eventService.EditSave(model);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Edit");
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id != null)
            {
                var @event = eventService.GetEventById(id);
                return PartialView("_Delete", @event);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                var ev = eventService.GetEventById(id);
                if (ev != null)
                {
                    await eventService.Delete(ev);
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

Task1_Homework/Task1_Homework/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Task1_Homework.Business;
using Task1_Homework.Business.Database;
using Task1_Homework.Business.Models;
using Task1_Homework.Business.Services.IServices;
using Task1_Homework.Models;

namespace Task1_Homework.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IOrderService orderService;
        private readonly ITicketService ticketService;

        public OrderController(UserManager<User> userManager, IOrderService orderService, ITicketService ticketService)
        {
            this.userManager = userManager;
            this.orderService = orderService;
            this.ticketService = ticketService;
        }

        public async Task<IActionResult> Create([FromRoute] int? id)
        {
            if (id != null)
            {
                var ticket = ticketService.GetTicketById(id);
                var buyer = await userManager.FindByNameAsync(User.Identity.Name);

                var model = new OrderCreateViewModel
                {
                    TicketId = ticket.Id,
                    BuyerId = buyer.Id
                };

                ViewData["EventName"] = ticket.Event.Name;
                ViewData["TicketPrice"] = ticket.Price;
                ViewData["BuyerName"] = buyer.UserName;

                return View("Create", model);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderCreateViewModel model)
        {
            if (ModelState.IsValid) {
                var order = new Order
                {
                    TicketId = model.TicketId,
                    BuyerId = model.BuyerId,                       
                    Status = TicketSaleStatus.Confirmation
                };
                await orderService.Save(order);
                return View("BuyRequest");
            }
            return RedirectToAction("Create", model);
        }

        public IActionResult BuyRequest()
        {            
            return View();
        }

        public IActionResult SalesRequests()
        {
            var orders = orderService.GetSalesRequestsForIdentityUser(User.Identity.Name).Result;

            if (orders != null)
            {
                var model = new OrderViewModel
                {
                    Orders = orders.ToArray()
                };

                return View(model);
            }

            return NotFound();
        }


        public IActionResult Accept([FromRoute] int? id)
        {
            if (id != null)
            {
                var order = orderService.GetOrderById(id);

                if (order != null)
                {
                    return PartialView("_Accept", order);
                }
            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Accept(Order model)
        {
            if (ModelState.IsValid)
            {
                var order = orderService.GetOrderById(model.Id);
                var user = await userManager.FindByNameAsync(HttpContext.User.Identity.Name);

                if (order.Ticket.SellerId != user.Id) 
                    return Forbid();

                await orderService.EditSave(order, model.TrackNumber);
                return RedirectToAction("SalesRequests");
            }
            return NotFound();
        }

        public IActionResult MyOrders()
        {
            var orders = orderService.GetOrdersForIdentityUser(User.Identity.Name).Result;

            if (orders != null)
            {
                var model = new OrderViewModel
                {
                    Orders = orders.ToArray()
                };

                return View(model);
            }

            return NotFound();
        }

        public async Task<IActionResult> Reject([FromRoute]int? id)
        {
            if (id != null)
            {
                var order = orderService.GetOrderById(id);
                order.Status = TicketSaleStatus.Rejected;
                await orderService.EditSave(order);

                return RedirectToAction("SalesRequests");
            }

            return NotFound();
        }

        public async Task<IActionResult> CancelOrder([FromRoute]int? id)
        {
            if (id != null)
            {
                await orderService.Delete(orderService.GetOrderById(id));
                return RedirectToAction("MyOrders");
            }

            return NotFound();
        }
    }
}

Task1_Homework/Task1_Homework/Views/Order/BuyRequest.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    ViewData["Title"] = "Order";
}

<div>
    <h4 class="loginpagetext buytext">@Localizer["Your request has been sent! <br />Wait for the seller's response"].</h4>
    
    <a asp-action="Index" asp-controller="Event" class="btnsend btnevlistback">Back to Event List</a>
</div>

Task1_Homework/Task1_Homework/Views/Order/Create.cshtml
@model OrderCreateViewModel

@{
    ViewData["Title"] = "Create Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="loginpagetext buytext">Create Order</h1>

<div class="row">
    <div class="col-md-4 blockorder">
        <div class=" ">
            <form asp-action="Create" class="maform" asp-controller="Order">
                @Html.HiddenFor(m => m.TicketId)
                @Html.HiddenFor(m => m.BuyerId)
                <div class="form-group">
                    <label class="control-label"><strong>Event:</strong></label>
                    @ViewData["EventName"]
                </div>
                <div class="form-group">
                    <label class="control-label"><strong>Price:</strong></label>
                    @ViewData["TicketPrice"]
                </div>
                <div class="form-group">
                    <label class="control-label"><strong>Buyer:</strong></label>
                    @ViewData["BuyerName"]
                </div>
                <input type="submit" value="Sent Order" class="btnsend btnsentorder"/>
                <a asp-action="Index" asp-controller="Event" class="btncancel">Cancel</a>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task1_Homework/Task1_Homework/Views/Order/MyOrders.cshtml
@model OrderViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Profile"];

}

<h3  class="loginpagetext buytext">Your Orders</h3>
<div class="block1">
    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>@Localizer["Event"]</th>
                <th>@Localizer["Price"]</th>
                <th>@Localizer["Status"]</th>
                <th>Track Number</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model.Orders.Reverse())
            {
                <tr>
                    <td>@order.Ticket.Event.Name</td>
                    <td>@order.Ticket.Price</td>
                    @if (order.Status == Task1_Homework.Business.TicketSaleStatus.Sold)
                    {
                        <td>@order.Status</td>
                        <td>@order.TrackNumber</td>
                    }
                    else if (order.Status == Task1_Homework.Business.TicketSaleStatus.Rejected)
                    {
                        <td>@order.Status</td>
                        <td>
                            @Html.ActionLink("Delete Order", "CancelOrder", "Order", new { id = order.Id, }, new { @class = "btncancel" })
                        </td>
                    }
                    else
                    {
                        <td>@order.Status</td>
                        <td>
                            @Html.ActionLink("Cancel the Order", "CancelOrder", "Order", new { id = order.Id, }, new { @class = "btnsendord" })
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

Task1_Homework/Task1_Homework/Views/Order/SalesRequests.cshtml
@model OrderViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    ViewData["Title"] = "SalesRequest";
}

<h1 class="loginpagetext buytext">@Localizer["Your requests for sale"]</h1>
<div class="block1">
    <table class="table">
        <thead>
            <tr>
                <th>@Localizer["Event"]</th>
                <th>@Localizer["Price"]</th>
                <th>@Localizer["Buyer"]</th>
                <th>@Localizer["Status"]</th>
                <th></th>
            </tr>
        </thead>
        <div id="modDialog" class="modal fade">
            <div id="dialogContent" class="modal-dialog"></div>
        </div>
        <tbody>
            @foreach (var order in Model.Orders.Reverse())
            {
                <tr>
                    <td>@order.Ticket.Event.Name</td>
                    <td>@order.Ticket.Price</td>
                    <td>@order.Buyer.UserName</td>
                    @if (order.Status == Task1_Homework.Business.TicketSaleStatus.Rejected)
                    {
                        <td>@order.Status</td>
                        <td>
                            @Html.ActionLink("Delete", "CancelOrder", "Order", new { id = order.Id, }, new { @class = "btncancel" })
                        </td>
                    }
                    else if (order.Status == Task1_Homework.Business.TicketSaleStatus.Sold)
                    {
                        <td>@order.Status</td>
                        <td>@order.TrackNumber</td>
                    }
                    else
                    {
                        <td>@order.Status</td>
                        <td>
                            @Html.ActionLink("Accept", "Accept", "Order", new { id = order.Id, }, new { @class = "btnsend compItem" }) |
                            @Html.ActionLink("Reject", "Reject", "Order", new { id = order.Id, }, new { @class = "btncancel" })
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts
{
    <script src="/dist/modulewindow.entry.js" type="module" defer></script>
}

Task1_Homework/Task1_Homework/Views/Order/_Accept.cshtml
@model Task1_Homework.Business.Models.Order

@{
    ViewData["Title"] = "Confirmation";
}

<div class="modal-content">
    <div class="modal-header">
        <h6>
            Enter track number for ticket:
        </h6>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body btnsg3">
            <div class="row">
                @Html.HiddenFor(m => m.Id)
                <dl class="row">
                    <dt class="col-sm-2">
                        <label class="control-label">Event:</label>
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Ticket.Event.Name)
                    </dd>
                    <dt class="col-sm-2">
                        <label class="control-label">Price:</label>
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Ticket.Price)
                    </dd>
                    <dt class="col-sm-2">
                        <label class="control-label">Buyer:</label>
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Buyer.UserName)
                    </dd>
                </dl>
                <form asp-action="Accept">
                    <div class="form-group">
                        <label asp-for="TrackNumber" class="control-label"><strong>TrackNumber:</strong></label>
                        <input asp-for="TrackNumber" class="form-control" />
                        <span asp-validation-for="TrackNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Accept" class="btn btn-primary" /> |
                        <a asp-action="SalesRequests" asp-controller="Order" class="btn  btn-danger">Cancel</a>
                    </div>
                </form>
            </div>  
    </div>
</div>

@section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}